import type { Product } from './types'

export const products: Product[] = [
  // SHIRTS
  {
    id: '1',
    name: 'Minimal Crew Neck',
    category: 'shirts',
    description: 'Classic crew neck tee in premium cotton. Timeless style meets everyday comfort.',
    basePrice: 45,
    rating: 4.8,
    reviews: 324,
    badge: 'Bestseller',
    variants: [
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/crew-black-1.jpg', '/images/products/crew-black-2.jpg'] },
      { color: 'White', colorCode: '#ffffff', images: ['/images/products/crew-white-1.jpg', '/images/products/crew-white-2.jpg'] },
      { color: 'Charcoal', colorCode: '#3a3a3a', images: ['/images/products/crew-charcoal-1.jpg', '/images/products/crew-charcoal-2.jpg'] },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
  },
  {
    id: '2',
    name: 'Oversized Button-Up',
    category: 'shirts',
    description: 'Relaxed fit button-up shirt. Perfect for layering or standalone style.',
    basePrice: 65,
    rating: 4.6,
    reviews: 156,
    badge: 'New',
    variants: [
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/button-black-1.jpg', '/images/products/button-black-2.jpg'] },
      { color: 'White', colorCode: '#ffffff', images: ['/images/products/button-white-1.jpg', '/images/products/button-white-2.jpg'] },
      { color: 'Navy', colorCode: '#001a4d', images: ['/images/products/button-navy-1.jpg', '/images/products/button-navy-2.jpg'] },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
  },
  {
    id: '3',
    name: 'Fitted Henley',
    category: 'shirts',
    description: 'Fitted henley with subtle texture. A wardrobe essential.',
    basePrice: 55,
    rating: 4.7,
    reviews: 203,
    badge: 'Trending',
    variants: [
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/henley-black-1.jpg', '/images/products/henley-black-2.jpg'] },
      { color: 'White', colorCode: '#ffffff', images: ['/images/products/henley-white-1.jpg', '/images/products/henley-white-2.jpg'] },
      { color: 'Gray', colorCode: '#808080', images: ['/images/products/henley-gray-1.jpg', '/images/products/henley-gray-2.jpg'] },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
  },
  {
    id: '4',
    name: 'Premium T-Shirt',
    category: 'shirts',
    description: 'Ultra-soft premium cotton blend. Comfort redefined.',
    basePrice: 50,
    rating: 4.9,
    reviews: 412,
    variants: [
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/premium-black-1.jpg', '/images/products/premium-black-2.jpg'] },
      { color: 'White', colorCode: '#ffffff', images: ['/images/products/premium-white-1.jpg', '/images/products/premium-white-2.jpg'] },
      { color: 'Cream', colorCode: '#fffdd0', images: ['/images/products/premium-cream-1.jpg', '/images/products/premium-cream-2.jpg'] },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
  },
  {
    id: '5',
    name: 'Vintage Graphic Tee',
    category: 'shirts',
    description: 'Retro-inspired graphic print on quality cotton.',
    basePrice: 48,
    rating: 4.5,
    reviews: 287,
    variants: [
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/graphic-black-1.jpg', '/images/products/graphic-black-2.jpg'] },
      { color: 'Navy', colorCode: '#001a4d', images: ['/images/products/graphic-navy-1.jpg', '/images/products/graphic-navy-2.jpg'] },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
  },

  // PANTS
  {
    id: '6',
    name: 'Slim Fit Chinos',
    category: 'pants',
    description: 'Sophisticated slim fit chinos for any occasion.',
    basePrice: 75,
    rating: 4.7,
    reviews: 198,
    badge: 'Bestseller',
    variants: [
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/chino-black-1.jpg', '/images/products/chino-black-2.jpg'] },
      { color: 'Khaki', colorCode: '#c3b091', images: ['/images/products/chino-khaki-1.jpg', '/images/products/chino-khaki-2.jpg'] },
      { color: 'Navy', colorCode: '#001a4d', images: ['/images/products/chino-navy-1.jpg', '/images/products/chino-navy-2.jpg'] },
    ],
    sizes: ['28', '30', '32', '34', '36', '38', '40'],
    inStock: true,
  },
  {
    id: '7',
    name: 'Premium Denim',
    category: 'pants',
    description: 'Raw denim with perfect fade potential. True classic.',
    basePrice: 95,
    rating: 4.8,
    reviews: 267,
    badge: 'New',
    variants: [
      { color: 'Dark Indigo', colorCode: '#1a1a3e', images: ['/images/products/denim-indigo-1.jpg', '/images/products/denim-indigo-2.jpg'] },
      { color: 'Light Blue', colorCode: '#87ceeb', images: ['/images/products/denim-light-1.jpg', '/images/products/denim-light-2.jpg'] },
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/denim-black-1.jpg', '/images/products/denim-black-2.jpg'] },
    ],
    sizes: ['28', '30', '32', '34', '36', '38'],
    inStock: true,
  },
  {
    id: '8',
    name: 'Relaxed Joggers',
    category: 'pants',
    description: 'Comfort meets style with our premium joggers.',
    basePrice: 65,
    rating: 4.6,
    reviews: 145,
    variants: [
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/jogger-black-1.jpg', '/images/products/jogger-black-2.jpg'] },
      { color: 'Gray', colorCode: '#808080', images: ['/images/products/jogger-gray-1.jpg', '/images/products/jogger-gray-2.jpg'] },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
  },
  {
    id: '9',
    name: 'Tapered Trousers',
    category: 'pants',
    description: 'Modern tapered fit with impeccable tailoring.',
    basePrice: 85,
    rating: 4.7,
    reviews: 176,
    badge: 'Trending',
    variants: [
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/trouser-black-1.jpg', '/images/products/trouser-black-2.jpg'] },
      { color: 'Charcoal', colorCode: '#3a3a3a', images: ['/images/products/trouser-charcoal-1.jpg', '/images/products/trouser-charcoal-2.jpg'] },
    ],
    sizes: ['28', '30', '32', '34', '36', '38'],
    inStock: true,
  },
  {
    id: '10',
    name: 'Cargo Pants',
    category: 'pants',
    description: 'Functional cargo pants with a modern twist.',
    basePrice: 70,
    rating: 4.5,
    reviews: 112,
    variants: [
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/cargo-black-1.jpg', '/images/products/cargo-black-2.jpg'] },
      { color: 'Olive', colorCode: '#808000', images: ['/images/products/cargo-olive-1.jpg', '/images/products/cargo-olive-2.jpg'] },
    ],
    sizes: ['28', '30', '32', '34', '36', '38'],
    inStock: true,
  },

  // SHORTS
  {
    id: '11',
    name: 'Chino Shorts',
    category: 'shorts',
    description: 'Classic chino shorts perfect for warm weather.',
    basePrice: 55,
    rating: 4.6,
    reviews: 143,
    badge: 'New',
    variants: [
      { color: 'Khaki', colorCode: '#c3b091', images: ['/images/products/short-khaki-1.jpg', '/images/products/short-khaki-2.jpg'] },
      { color: 'Navy', colorCode: '#001a4d', images: ['/images/products/short-navy-1.jpg', '/images/products/short-navy-2.jpg'] },
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/short-black-1.jpg', '/images/products/short-black-2.jpg'] },
    ],
    sizes: ['28', '30', '32', '34', '36'],
    inStock: true,
  },
  {
    id: '12',
    name: 'Athletic Shorts',
    category: 'shorts',
    description: 'Lightweight and breathable for active days.',
    basePrice: 45,
    rating: 4.7,
    reviews: 267,
    badge: 'Bestseller',
    variants: [
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/athletic-black-1.jpg', '/images/products/athletic-black-2.jpg'] },
      { color: 'Navy', colorCode: '#001a4d', images: ['/images/products/athletic-navy-1.jpg', '/images/products/athletic-navy-2.jpg'] },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
  },
  {
    id: '13',
    name: 'Denim Shorts',
    category: 'shorts',
    description: 'Classic denim cutoffs with timeless appeal.',
    basePrice: 50,
    rating: 4.4,
    reviews: 98,
    variants: [
      { color: 'Light Blue', colorCode: '#87ceeb', images: ['/images/products/dshort-light-1.jpg', '/images/products/dshort-light-2.jpg'] },
      { color: 'Dark Blue', colorCode: '#00008b', images: ['/images/products/dshort-dark-1.jpg', '/images/products/dshort-dark-2.jpg'] },
    ],
    sizes: ['28', '30', '32', '34', '36'],
    inStock: true,
  },
  {
    id: '14',
    name: 'Linen Shorts',
    category: 'shorts',
    description: 'Breathable linen for ultimate summer comfort.',
    basePrice: 60,
    rating: 4.8,
    reviews: 187,
    badge: 'Trending',
    variants: [
      { color: 'Natural', colorCode: '#f5deb3', images: ['/images/products/linen-natural-1.jpg', '/images/products/linen-natural-2.jpg'] },
      { color: 'White', colorCode: '#ffffff', images: ['/images/products/linen-white-1.jpg', '/images/products/linen-white-2.jpg'] },
    ],
    sizes: ['28', '30', '32', '34', '36'],
    inStock: true,
  },

  // JACKETS
  {
    id: '15',
    name: 'Wool Blazer',
    category: 'jackets',
    description: 'Tailored wool blazer for sophisticated style.',
    basePrice: 180,
    rating: 4.9,
    reviews: 234,
    badge: 'Bestseller',
    variants: [
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/blazer-black-1.jpg', '/images/products/blazer-black-2.jpg'] },
      { color: 'Navy', colorCode: '#001a4d', images: ['/images/products/blazer-navy-1.jpg', '/images/products/blazer-navy-2.jpg'] },
      { color: 'Charcoal', colorCode: '#3a3a3a', images: ['/images/products/blazer-charcoal-1.jpg', '/images/products/blazer-charcoal-2.jpg'] },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
  },
  {
    id: '16',
    name: 'Denim Jacket',
    category: 'jackets',
    description: 'Iconic denim jacket for timeless versatility.',
    basePrice: 120,
    rating: 4.7,
    reviews: 312,
    variants: [
      { color: 'Dark Indigo', colorCode: '#1a1a3e', images: ['/images/products/djacket-indigo-1.jpg', '/images/products/djacket-indigo-2.jpg'] },
      { color: 'Light Blue', colorCode: '#87ceeb', images: ['/images/products/djacket-light-1.jpg', '/images/products/djacket-light-2.jpg'] },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
  },
  {
    id: '17',
    name: 'Bomber Jacket',
    category: 'jackets',
    description: 'Classic bomber with modern refinement.',
    basePrice: 140,
    rating: 4.6,
    reviews: 198,
    badge: 'New',
    variants: [
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/bomber-black-1.jpg', '/images/products/bomber-black-2.jpg'] },
      { color: 'Olive', colorCode: '#808000', images: ['/images/products/bomber-olive-1.jpg', '/images/products/bomber-olive-2.jpg'] },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
  },
  {
    id: '18',
    name: 'Leather Moto Jacket',
    category: 'jackets',
    description: 'Premium leather moto jacket. Bold and timeless.',
    basePrice: 250,
    rating: 4.8,
    reviews: 156,
    badge: 'Trending',
    variants: [
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/moto-black-1.jpg', '/images/products/moto-black-2.jpg'] },
      { color: 'Brown', colorCode: '#8b4513', images: ['/images/products/moto-brown-1.jpg', '/images/products/moto-brown-2.jpg'] },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
  },
  {
    id: '19',
    name: 'Lightweight Puffer',
    category: 'jackets',
    description: 'Compact puffer jacket for all-season layering.',
    basePrice: 110,
    rating: 4.5,
    reviews: 187,
    variants: [
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/puffer-black-1.jpg', '/images/products/puffer-black-2.jpg'] },
      { color: 'Navy', colorCode: '#001a4d', images: ['/images/products/puffer-navy-1.jpg', '/images/products/puffer-navy-2.jpg'] },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
  },
  {
    id: '20',
    name: 'Wool Coat',
    category: 'jackets',
    description: 'Premium wool overcoat for elegant warmth.',
    basePrice: 220,
    rating: 4.7,
    reviews: 143,
    variants: [
      { color: 'Black', colorCode: '#1a1a1a', images: ['/images/products/coat-black-1.jpg', '/images/products/coat-black-2.jpg'] },
      { color: 'Charcoal', colorCode: '#3a3a3a', images: ['/images/products/coat-charcoal-1.jpg', '/images/products/coat-charcoal-2.jpg'] },
      { color: 'Gray', colorCode: '#808080', images: ['/images/products/coat-gray-1.jpg', '/images/products/coat-gray-2.jpg'] },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
  },
]
